<?php

xautoload()->registerModulePsr4(__FILE__, 'src');

use Drupal\panelizer_deploy\ConverterMap;
use Drupal\panelizer_deploy\ConverterException;
use Drupal\panelizer_deploy\DisplayConverter;
use Drupal\panelizer_deploy\EntityConverter;
use Drupal\panelizer_deploy\PaneConverter;

/**
 * Implements hook_deploy_entity_dependencies().
 */
function panelizer_deploy_entity_dependencies($entity, $entity_type) {
  if (panelizer_deploy_is_panelizer($entity, $entity_type)) {
    $info = entity_get_info();
    $entity_keys = array_keys($info);

    ctools_include('content');
    $dependencies = array();
    foreach ($entity->panelizer as $view_mode) {
      foreach ($view_mode->display->content as $pid => $pane) {
        if ($pane->type == 'fieldable_panels_pane') {
          list($idtype, $id) = explode(':', $pane->subtype);
          if ($idtype == 'fpid') {
            entity_dependency_add($dependencies, (object)array('fpid' => $id), 'fieldable_panels_pane', 'fpid');
          }
          else {
            $ids = entity_get_id_by_uuid('fieldable_panels_pane', array($id));
            entity_dependency_add($dependencies, (object)array('fpid' => reset($ids)), 'fieldable_panels_pane', 'fpid');
          }
        } elseif (isset($entity_keys[$pane->type]) && $pane->type == $pane->subtype) {
          // Does this entity support uuid
          // Does this catch more then node?
          if (isset($info[$pane->type]['entity keys']['uuid'])) {
            entity_dependency_add(
              $dependencies,
              (object) $pane->configuration,
              $pane->type,
              $info[$pane->type]['entity keys']['id']);
          }
        }

        if (!empty($pane->contexts)) {
          foreach ($pane->contexts as $id => $context) {
            if ($matches = panelizer_deploy_get_entity_ids_from_context($context)) {
              entity_dependency_add($dependencies, (object)$context, $matches[1], 'entity_id');
            }
          }
        }
      }
    }

    return $dependencies;
  }
}

/**
 * Get the entity id's from a context
 *
 * @param $context string
 * @return array
 */
function panelizer_deploy_get_entity_ids_from_context($context) {
  preg_match('/^entity:(\w+)$/', $context['name'], $matches);
  return $matches;
}

/**
 * Is this entity panelized
 *
 * @param $entity stdClass
 * @param $entity_type string
 * @return boolean|PanelizerEntityInterface
 */
function panelizer_deploy_is_panelizer($entity, $entity_type) {
  $static = &drupal_static(__FUNCTION__, array());

  if (!isset($static[$entity_type])) {
    $static[$entity_type] = array();
  }

  list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);

  if (!isset($static[$entity_type][$bundle])) {
    if ($handler = panelizer_entity_plugin_get_handler($entity_type)) {
      // Get all of the entity types that have uuid enables

      if ($handler->is_panelized($bundle)) {
        $static[$entity_type][$bundle] = $handler;
      } else {
        $static[$entity_type][$bundle] = FALSE;
      }
    } else {
      $static[$entity_type][$bundle] = FALSE;
    }
  }


  return $static[$entity_type][$bundle];
}


/**
 * Implements hook_entity_uuid_load().
 */
function panelizer_deploy_entity_uuid_load(&$entities, $entity_type) {
  $converter = new ConverterMap();
  $converter->addConverterType(new PaneConverter(), "panels_pane");
  $converter->addConverterType(new DisplayConverter(), "panels_display");

  foreach($entities as &$entity) {
    if (panelizer_deploy_is_panelizer($entity, $entity_type)) {

      // get the uuid key for this entity
      // The uuid should already be set on the entity
      $info = entity_get_info();
      $entity_keys = array_keys($info);

      foreach ($entity->panelizer as &$view_mode) {
        // If this is not a custom panel
        if ($view_mode->did) {

          $view_mode->entity_id = $entity->{$info[$entity_type]['entity keys']['uuid']};

          if (isset($view_mode->revision_id) && isset($info[$entity_type]['entity keys']['revision uuid'])) {
            $view_mode->revision_id = $entity->{$info[$entity_type]['entity keys']['revision uuid']};
          }

          // update display id
          // No need for the converter here since we know it's part of the object
          $view_mode->did = $view_mode->display->uuid;
          $view_mode->display->did = $view_mode->display->uuid;

          $new_panes = array();
          foreach ($view_mode->display->content as $pid => &$doNotUse) {
            $new_pane = $view_mode->display->clone_pane($pid);

            // uuid pane and display
            $new_pane->pid = $new_pane->uuid;
            $new_pane->did = $view_mode->display->uuid;

            // From other entities
            // Does this catch more then node?
            if (isset($entity_keys[$new_pane->type]) && $new_pane->type == $new_pane->subtype) {
              // Does this entity support uuid
              if (isset($info[$new_pane->type]['entity keys']['uuid'])) {
                $type_info = $info[$new_pane->type];
                if (is_numeric($new_pane->configuration[$type_info['entity keys']['id']])) {
                  $converter_key = "entity-{$new_pane->type}";
                  try {
                    $converter->getConverterType($converter_key);
                  } catch (ConverterException $e) {
                    $converter->addConverterType(new EntityConverter($new_pane->type), $converter_key);
                  }

                  $converter->addObject($new_pane->configuration, $converter_key);
                }
              }
            }

            /* @TODO this needs reworking
            if (!empty($new_pane->contexts)) {
              foreach ($new_pane->contexts as $id => $context) {
                if ($matches = panelizer_deploy_get_entity_ids_from_context($context)) {
                  $converter_key = "entity-{$context[1]}";
                  try {
                    $converter->getConverterType($converter_key);
                  } catch (ConverterException $e) {
                    $converter->addConverterType(new EntityConverter($new_pane->type), $converter_key);
                  }

                  $converter->addObject($context, $converter_key);
                }
              }
            }*/

            $new_panes[$new_pane->uuid] = $new_pane;
          }

          // Update the panels
          foreach ($view_mode->display->panels as &$panel) {
            foreach ($panel as &$pid) {
              $pid = $view_mode->display->content[$pid]->uuid;
            }
          }

          $view_mode->display->content = $new_panes;
        }
      }
    }
  }

  $converter->convertToUUID();
}

/**
 * Implements hook_entity_uuid_presave().
 */
function panelizer_entity_uuid_presave(&$entity, $entity_type) {
  if (panelizer_deploy_is_panelizer($entity, $entity_type)) {
    $converter = new ConverterMap();
    $converter->addConverterType(new PaneConverter(), "panels-pane")
      ->addConverterType(new DisplayConverter(), "panels-display")
      ->addConverterType(new PaneConverter(), 'panels-pane');


    $info = entity_get_info();
    $entity_keys = array_keys($info);

    foreach ($entity->panelizer as &$view_mode) {
      // If this is not a custom panel
      if ($view_mode->did) {

        $view_mode->entity_id = $entity->{$info[$entity_type]['entity keys']['id']};

        if (isset($view_mode->revision_id) && isset($info[$entity_type]['entity keys']['revision'])) {
          $view_mode->revision_id = $entity->{$info[$entity_type]['entity keys']['revision']};
        }

        // update display id
        // No need for the converter here since we know it's part of the object
        $converter->addObject($view_mode, 'panels_display');
        $converter->addObject($view_mode->display, 'panels_display');

        $new_panes = array();
        foreach ($view_mode->display->content as $pid => &$doNotUse) {
          $new_pane = $view_mode->display->clone_pane($pid);

          // uuid pane and display
          $converter->addObject($new_pane, 'panels_pane');
          $converter->addObject($new_pane, 'panels_display');

          // From other entities
          // Does this catch more then node?
          if (isset($entity_keys[$new_pane->type]) && $new_pane->type == $new_pane->subtype) {
            // Does this entity support uuid
            if (isset($info[$new_pane->type]['entity keys']['uuid'])) {
              $converter_key = "entity-{$new_pane->type}";
              try {
                $converter->getConverterType($converter_key);
              } catch (ConverterException $e) {
                $converter->addConverterType(new EntityConverter($new_pane->type), $converter_key);
              }

              $converter->addObject($new_pane->configuration, $converter_key);
            }
          }

          /* @todo this needs reworking
          if (!empty($new_pane->contexts)) {
            foreach ($new_pane->contexts as $id => $context) {
              if ($matches = panelizer_deploy_get_entity_ids_from_context($context)) {
                $converter_key = "entity-{$context[1]}";
                try {
                  $converter->getConverterType($converter_key);
                } catch (ConverterException $e) {
                  $converter->addConverterType(new EntityConverter($new_pane->type), $converter_key);
                }

                $converter->addObject($context, $converter_key);
              }
            }
          }*/

          $new_panes[$new_pane->uuid] = $new_pane;
        }

        // Update the panels
        foreach ($view_mode->display->panels as &$panel) {
          foreach ($panel as &$pid) {
            $pid = $view_mode->display->content[$pid]->pid;
          }
        }

        $view_mode->display->content = $new_panes;
      }
    }
  }

  $converter->convertToID();
}

